server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file://C:\Users\qkqhe\msa-service-discovery # ?? ??
          # git
#          uri: https://github.com/Kimminwoo6039/MSA_study.git
#          username: [user name]
#          password: [password]