server:
  port: 8888

spring:
  application:
    name: config-server

  # 로컬에서 읽기
  profiles:
    active: native

  cloud:
    config:
      server:
        # 로컬 읽기
        native:
          search-locations: file://${user.home}/qkqhm/test
        # / 로컬읽기
        git:
          uri: file://C:\Users\qkqhe\msa-service-discovery # ?? ??
          # git
#          uri: https://github.com/Kimminwoo6039/MSA_study.git
#          username: [user name]
#          password: [password]